#
# GitLeaks Repo Specific Configuration
#
# This allowlist is used to help Red Hat ignore false positives during its code
# scans.

[allowlist]
  paths = [
    '''test-data/test-rsa.pem''',
    '''keylime/test-data/test-rsa.pem''',
    '''keylime/test-data/prime256v1.pem''',
  ]
