language: rust
dist: xenial

before_script:
    - rustup component add rustfmt-preview

before_install:
    - sudo apt-get install -y python3

script:
    - cargo fmt --all -- --check
    - cargo build
    - cargo test
    - ./.travis/nopanic.py
