[package]
name = "keylime"
description = "Shared utilities for Keylime crates"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
base64.workspace = true
hex.workspace = true
log.workspace = true
openssl.workspace = true
pest.workspace = true
pest_derive.workspace = true
serde.workspace = true
serde_derive.workspace = true
static_assertions.workspace = true
thiserror.workspace = true
tss-esapi.workspace = true
picky-asn1-der.workspace = true
picky-asn1-x509.workspace = true

[dev-dependencies]
tempfile.workspace = true
