[package]
name = "keylime"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
hex = "0.4"
log = "0.4"
openssl = "0.10.15"
serde = "1.0.80"
serde_derive = "1.0.80"
static_assertions = "1"
thiserror = "1.0"
tss-esapi = {version = "7.2.0", features = ["generate-bindings"]}

[dev-dependencies]
tempfile = "3.0.4"
