[package]
name = "keylime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
openssl = "0.10.15"
serde = "1.0.80"
serde_derive = "1.0.80"
thiserror = "1.0"
tss-esapi = "7.1.0"

[dev-dependencies]
tempfile = "3.0.4"
