---
name: No-Warnings Compilation

"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  basic-compilation:
    name: Compilation with no warnings
    runs-on: ubuntu-latest
    container:
      # To refresh: skopeo inspect --no-tags docker://quay.io/keylime/keylime-ci:latest | jq -r '.Digest'
      image: quay.io/keylime/keylime-ci@sha256:973f36045d0dd0b1a219dd88f06625c65a77f267842ee23d955e0c095ef09ff2
    steps:
      - uses: actions/checkout@v6
      - name: Set git safe.directory for the working directory
        run: git config --system --add safe.directory "$PWD"
      - name: Check compilation (no warnings)
        run: RUSTFLAGS="-D warnings" cargo build
      - name: Check test compilation (no warnings)
        run: RUSTFLAGS="-D warnings" cargo test --no-run
      - name: Check clippy errors (no warnings included)
        run: cargo clippy --all-features --all-targets -- -D clippy::all -D warnings
